-- Script was generated by Devart Entity Developer, Version 7.3.290.0
-- Script date 2025. 11. 21. 23:34:52
-- Target Server: SQL Server
-- Server Version: 2022

-- 
-- Creating a table dbo.Helyseg 
-- 
CREATE TABLE dbo.Helyseg (
   Id INT NOT NULL IDENTITY,
   IRSZ NVARCHAR(25) NOT NULL,
   Nev NVARCHAR(4000) NOT NULL,
   CONSTRAINT PK_Helyseg PRIMARY KEY (Id)
)
GO

-- 
-- Creating a table dbo.Szemely 
-- 
CREATE TABLE dbo.Szemely (
   Id INT NOT NULL IDENTITY,
   Vezeteknev NVARCHAR(4000) NOT NULL,
   Utonev NVARCHAR(4000) NOT NULL,
   Lakcim NVARCHAR(4000) NOT NULL,
   enHelysegId INT,
   Felhasznalonev NVARCHAR(50) NOT NULL,
   JelszoHash NVARCHAR(200) NOT NULL,
   CONSTRAINT PK_Szemely PRIMARY KEY (Id),
   CONSTRAINT FK_Szemely_Helyseg_0 FOREIGN KEY (enHelysegId) REFERENCES dbo.Helyseg (Id) ON DELETE NO ACTION
)
GO

-- 
-- Creating a table dbo.Telefonszam 
-- 
CREATE TABLE dbo.Telefonszam (
   Id INT NOT NULL IDENTITY,
   Szam NVARCHAR(25) NOT NULL,
   enSzemelyId INT,
   CONSTRAINT PK_Telefonszam PRIMARY KEY (Id),
   CONSTRAINT FK_Telefonszam_Szemely_0 FOREIGN KEY (enSzemelyId) REFERENCES dbo.Szemely (Id) ON DELETE NO ACTION
)
GO

