//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 11. 19. 20:02:16
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Model
{
    public partial class enHelyseg {

        public enHelyseg()
        {
            this.enSzemelyek = new List<enSzemely>();
            OnCreated();
        }

        public int Id { get; set; }

        public string IRSZ { get; set; }

        public string Nev { get; set; }


        public virtual IList<enSzemely> enSzemelyek { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
